#!/bin/sh
## conohav2 api

## identity API: get a token
## https://doc.conoha.jp/api-vps2/identity-post_tokens-v2/

## requires api_user, password, tenantID
conoha_get_token(){

  typeset api_user
  typeset password
  typeset tenantID
  typeset CONOHACONFIG=".conoha_config"
  . "${CONOHACONFIG}"
  ## now available: api_user, password, tenantID

  typeset request_json="{\"auth\": {\"passwordCredentials\": {\"username\": \"${api_user}\", \"password\": \"${password}\"}, \"tenantId\": \"${tenantID}\"}}"

  ## echo "request_json:" 1>&2
  ## echo "${request_json}" 1>&2

  curl --silent -X POST \
    -H "Accept: application/json" \
    -d "${request_json}" \
    https://identity.tyo1.conoha.io/v2.0/tokens |\
  jq --raw-output .access.token.id

}

conoha_get_tenantID(){
  typeset tenantID
  typeset CONOHACONFIG=".conoha_config"
  . "${CONOHACONFIG}"
  ## now available: api_user, password, tenantID
  echo "${tenantID}"
}
